### ISSUE TITLE
Rewrite this in a real language

### ISSUE THREAD

**Issue by mizlan** [mizlan/usub#1]

**Comment by Shad0wSeven** [comment]
**yeah use nim**
https://nim-lang.org/

**Comment by mizlan** [comment]
Nim has issues on many fronts though. Choose again.

**Comment by Shad0wSeven** [comment]
https://fortran-lang.org/

**Comment by mizlan** [comment]
Let's not.

**Comment by Shad0wSeven** [comment]
https://www.java.com/en/
:kekw: jkjkjk im joking

actually how about https://www.javascript.com/

**Comment by mizlan** [comment]
I want to close this issue but on the other hand I need to leave this open.

**Comment by AndreiSva** [comment]
How about rust? It's a language meant for this kind of thing.

**Comment by mizlan** [comment]
That sounds like a great idea! Unfortunately I don't know Rust but don't _exactly_ plan on learning it at the moment. Does Haskell/Clojure deviate a little too much?

**Comment by mizlan** [comment]
Nah
